# Generated by Django 2.0 on 2017-12-11 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='language',
            field=models.CharField(choices=[('e', 'English'), ('c', 'Chinese'), ('f', 'French')], default='e', help_text='select the languge of this book', max_length=1),
        ),
    ]
